version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - mysql
    command: ["/main"]
    networks:
      - app-network

  go_executor:
    build:
      context: ./running_user_code/go
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - mysql
    # Set entrypoint to empty for running on API call only
    entrypoint: [""]

  python_executor:
    build:
      context: ./running_user_code/python
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - mysql
    # Set entrypoint to empty for running on API call only
    entrypoint: [""]

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
