apiVersion: v1
kind: Service
metadata:
  name: leetcode-backend-service
spec:
  selector:
    app: leetcode-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
