# Use the official Python image, version 3.11
FROM python:3.11

# Set the working directory inside the container
WORKDIR /app

# Copy user Python code into the container
COPY user_code.py .

# Execute the Python code
CMD ["python3", "user_code.py"]
